name: "Build Flipper Zero App"

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  build-fap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build FAP with uFBT
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        id: build
        with:
          sdk-channel: dev
          app-dir: roger_bruteforce

      - name: Upload FAP Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build.outputs.suffix }}
          path: ${{ steps.build.outputs.fap-artifacts }}
